[package]
name = "samples"
version = "0.1.0"
authors = ["Oleg perchykoleg@gmail.com"]
description = "Testing out how to publish crates"
license = "MIT"
edition = "2021"

[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
